//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabyrinthEntities : DbContext
    {
        public LabyrinthEntities()
            : base("name=LabyrinthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<FriendList> FriendList { get; set; }
        public virtual DbSet<FriendRequest> FriendRequest { get; set; }
        public virtual DbSet<PlayerSkins> PlayerSkins { get; set; }
        public virtual DbSet<Preferences> Preferences { get; set; }
        public virtual DbSet<Skin> Skin { get; set; }
        public virtual DbSet<Stats> Stats { get; set; }
        public virtual DbSet<VerificationCode> VerificationCode { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
