//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerSkins
    {
        public int idPlayerSkins { get; set; }
        public int idUser { get; set; }
        public int idSkin { get; set; }
    
        public virtual Skin Skin { get; set; }
        public virtual User User { get; set; }
    }
}
