//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferences
    {
        public int idPreference { get; set; }
        public int lastPickedSkin { get; set; }
        public int idUser { get; set; }
        public Nullable<int> lastPickedGameboard { get; set; }
    
        public virtual User User { get; set; }
    }
}
